// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    IMdiEmoticonHappyOutline: typeof import('~icons/mdi/emoticon-happy-outline')['default']
    IMdiEmoticonSadOutline: typeof import('~icons/mdi/emoticon-sad-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
